# Generated by Django 2.1.4 on 2018-12-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_id',
            field=models.CharField(max_length=32, unique=True, editable=False, default='something_unique'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('source', 'external_id')},
        ),
    ]
